<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2025-07-15T23:14:40.000Z" hostname="https://orgfarm-7d18613451-dev-ed.develop.my.salesforce.com" tests="1" failures="1"  errors="0"  time="0.40">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Tue Jul 15 2025 6:14:40 PM"/>
            <property name="testSetupTimeInMs" value="0"/>
            <property name="testExecutionTime" value="0.40 s"/>
            <property name="testTotalTime" value="0.40 s"/>
            <property name="commandTime" value="0.60 s"/>
            <property name="hostname" value="https://orgfarm-7d18613451-dev-ed.develop.my.salesforce.com"/>
            <property name="orgId" value="00DgK000001suJEUAY"/>
            <property name="username" value="dany338919@agentforce.com"/>
            <property name="testRunId" value="707gK000008tK9t"/>
            <property name="userId" value="005gK000001VTlBQAW"/>
        </properties>
        <testcase name="testFlowInvocadoConAccount" classname="FlowInvokerTest" time="0.40">
            <failure message="System.AssertException: Assertion Failed: No se encontrÃ³ una tarea con el asunto esperado."><![CDATA[Class.FlowInvokerTest.testFlowInvocadoConAccount: line 35, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
